"""add_forecasting_tables

Revision ID: 3458c50f4214
Revises: 1fb668d2ed0f
Create Date: 2026-05-31 17:19:23.733732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3458c50f4214'
down_revision: Union[str, Sequence[str], None] = '1fb668d2ed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('r2_score', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_models')),
    sa.UniqueConstraint('name', 'version', name='uq_forecast_model_name_version')
    )
    op.create_table('forecast_runs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_model_id', sa.UUID(), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_model_id'], ['forecast_models.id'], name=op.f('fk_forecast_runs_forecast_model_id_forecast_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forecast_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_table('forecast_predictions',
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('forecast_month', sa.Date(), nullable=False),
    sa.Column('predicted_income', sa.Float(), nullable=False),
    sa.Column('predicted_expenses', sa.Float(), nullable=False),
    sa.Column('predicted_savings', sa.Float(), nullable=False),
    sa.Column('predicted_cashflow', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], name=op.f('fk_forecast_predictions_forecast_run_id_forecast_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_predictions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_predictions')
    op.drop_table('forecast_runs')
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
